/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'timestamp' : Time,
  'senderName' : IDL.Text,
  'upiId' : IDL.Text,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addTransaction' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getTodaysSummary' : IDL.Func(
      [],
      [IDL.Record({ 'totalAmount' : IDL.Nat, 'transactionCount' : IDL.Nat })],
      ['query'],
    ),
  'seedDemoTransactions' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'timestamp' : Time,
    'senderName' : IDL.Text,
    'upiId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addTransaction' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getTodaysSummary' : IDL.Func(
        [],
        [IDL.Record({ 'totalAmount' : IDL.Nat, 'transactionCount' : IDL.Nat })],
        ['query'],
      ),
    'seedDemoTransactions' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };