/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'status' : string,
  'timestamp' : Time,
  'senderName' : string,
  'upiId' : string,
  'amount' : bigint,
}
export interface _SERVICE {
  'addTransaction' : ActorMethod<[bigint, string, string, string], bigint>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getTodaysSummary' : ActorMethod<
    [],
    { 'totalAmount' : bigint, 'transactionCount' : bigint }
  >,
  'seedDemoTransactions' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];